[package]
name = "distribuidos_tp1_gateway"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "API Gateway defined for TP1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
distribuidos_tp1_protocols = "1.2.6"
distribuidos_types = "0.1.0"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
