[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
distribuidos_tp1_protocols = "1.1.3"
distribuidos_types = "0.1.0"
log = "0.4"
pretty_env_logger = "0.4"
