version: '3'

services:
  event_writer:
    container_name: tp1_event_writer
    image: tp1_event_writer:latest
    build: ./services/event_writer
    entrypoint: target/release/event_writer
    environment:
      - RUST_LOG=debug
    networks:
      - external_apps
      - internal
    volumes:
      - database:/events:rw

  public_aggregator:
    container_name: tp1_public_aggregator
    image: tp1_aggregator:latest
    build: ./services/aggregator
    entrypoint: target/release/aggregator
    environment:
      - RUST_LOG=debug
    networks:
      - external_users
      - internal
    volumes:
      - database:/events:ro

  internal_aggregator:
    container_name: tp1_internal_aggregator
    image: tp1_aggregator:latest
    build: ./services/aggregator
    entrypoint: target/release/aggregator
    environment:
      - RUST_LOG=debug
    networks:
      - internal
    volumes:
      - database:/events:ro

  alert_service:
    container_name: tp1_alert_service
    image: tp1_alert_service:latest
    build: ./services/alert_service
    entrypoint: target/release/alert_service
    networks:
      - internal

  logging_service:
    container_name: tp1_logging_service
    image: tp1_logging_service:latest
    build: ./services/logging_service
    entrypoint: target/release/logging_service
    networks:
      - internal

  app:
    container_name: tp1_app
    image: tp1_app:latest
    build: ./services/app
    entrypoint: target/release/app
    networks:
      - external_apps

  client:
    container_name: tp1_client
    image: tp1_client:latest
    build: ./services/client
    entrypoint: target/release/client
    environment:
      - RUST_LOG=debug
    networks:
      - external_users

networks:
  external_apps:
    driver: bridge
  external_users:
    driver: bridge
  internal:
    driver: bridge

volumes:
  database:
