version: '3'

services:
  event_writer:
    image: tp1_event_writer:latest
    build: ./services/event_writer
    entrypoint: target/release/main
    environment:
      - RUST_LOG=info
    networks:
      - external_apps
      - internal
    volumes:
      # - database:/usr/app/events:rw
      - ./events:/usr/app/events:rw
      - ./config/event_writer:/usr/app/config:ro

  public_aggregator:
    image: tp1_aggregator:latest
    build: ./services/aggregator
    entrypoint: target/release/main
    environment:
      - RUST_LOG=info
    networks:
      - external_clients
      - internal
    volumes:
      # - database:/usr/app/events:ro
      - ./events:/usr/app/events:ro
      - ./config/public_aggregator:/usr/app/config:ro

  internal_aggregator:
    image: tp1_aggregator:latest
    build: ./services/aggregator
    entrypoint: target/release/main
    environment:
      - RUST_LOG=info
    networks:
      - internal
    volumes:
      # - database:/usr/app/events:ro
      - ./events:/usr/app/events:ro
      - ./config/internal_aggregator:/usr/app/config:ro

  alert_service:
    image: tp1_alert_service:latest
    build: ./services/alert_service
    entrypoint: target/release/main
    environment:
      - RUST_LOG=info
    networks:
      - internal
    volumes:
      - ./config/alert_service:/usr/app/config:ro
    depends_on:
      - internal_aggregator

  app:
    image: tp1_app:latest
    build: ./services/app
    entrypoint: target/release/simulated
    environment:
      - RUST_LOG=info
    networks:
      - external_apps
    volumes:
      - ./config/app:/usr/app/config:ro
    depends_on:
      - event_writer

  client:
    image: tp1_client:latest
    build: ./services/client
    entrypoint: target/release/simulated
    environment:
      - RUST_LOG=info
    networks:
      - external_clients
    volumes:
      - ./config/client:/usr/app/config:ro
    depends_on:
      - public_aggregator

networks:
  external_apps:
    driver: bridge
  external_clients:
    driver: bridge
  internal:
    driver: bridge

volumes:
  database:
