version: '3'

services:
  event_receiver:
    container_name: tp1_event_receiver
    image: tp1_event_receiver:latest
    build: ./services/event_receiver
    entrypoint: target/release/event_receiver
    environment:
      - RUST_LOG=debug
    networks:
      - external_apps
      - internal

  query_receiver:
    container_name: tp1_query_receiver
    image: tp1_query_receiver:latest
    build: ./services/query_receiver
    entrypoint: target/release/query_receiver
    networks:
      - external_users
      - internal

  alert_service:
    container_name: tp1_alert_service
    image: tp1_alert_service:latest
    build: ./services/alert_service
    entrypoint: target/release/alert_service
    networks:
      - internal

  db_aggregator:
    container_name: tp1_db_aggregator
    image: tp1_db_aggregator:latest
    build: ./services/db_aggregator
    entrypoint: target/release/db_aggregator
    environment:
      - RUST_LOG=debug
    networks:
      - internal
    volumes:
      - database:/events:ro

  db_event_writer:
    container_name: tp1_db_event_writer
    image: tp1_db_event_writer:latest
    build: ./services/db_event_writer
    entrypoint: target/release/db_event_writer
    environment:
      - RUST_LOG=debug
    networks:
      - internal
    volumes:
      - database:/events:rw

  logging_service:
    container_name: tp1_logging_service
    image: tp1_logging_service:latest
    build: ./services/logging_service
    entrypoint: target/release/logging_service
    networks:
      - internal

  app:
    container_name: tp1_app
    image: tp1_app:latest
    build: ./services/app
    entrypoint: target/release/app
    networks:
      - external_apps

  client:
    container_name: tp1_client
    image: tp1_client:latest
    build: ./services/client
    entrypoint: target/release/client
    environment:
      - RUST_LOG=debug
    networks:
      - external_users

networks:
  external_apps:
    driver: bridge
  external_users:
    driver: bridge
  internal:
    driver: bridge

volumes:
  database:
