[package]
name = "distribuidos_tp1_utils"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Common utils defined for TP1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
log = "0.4"
fs2 = "0.4.3"
distribuidos_tp1_protocols = "1.1.2"
