# Paths
CONFIG_DIRPATH = '/config'
COMMON_CONFIG_FILEPATH = f'{CONFIG_DIRPATH}/common.json'
INGESTION_CONFIG_FILEPATH = f'{CONFIG_DIRPATH}/ingestion.json'
SINK_CONFIG_FILEPATH = f'{CONFIG_DIRPATH}/sink.json'

# Others
DEFAULT_EXTENSION = '.png'
