#!/bin/sh

set -e

# Run CI pre-commit hook only on staged files

# git diff --full-index --binary > /tmp/stash.$$
# git stash -q --keep-index

# .github/hooks/cargo-checks
# RESULT=$?

# git apply --whitespace=nowarn < /tmp/stash.$$ &> /dev/null && git stash drop -q
# rm /tmp/stash.$$

# exit $RESULT
