[package]
name = "distribuidos_example_package"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Example package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
