[package]
name = "distribuidos_tp1_protocols"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Communication protocols defined for TP1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
distribuidos_types = "0.1.0"
distribuidos_utils = "0.1.0"
