version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: target/release/app
    environment:
      - SERVER_PORT=12345
      - RUST_LOG=trace
    volumes:
      - ./server/config:/usr/app/config:ro
    networks:
      - testing_net
{% for n in range(1, n_clients + 1) %}
  client{{n}}:
    container_name: client{{n}}
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID={{n}}
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_LOOP_LAPSE=1m2s
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
{% endfor %}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
