[package]
name = "distribuidos_utils"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Common utils using standard library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
