name: 'Lint package: ingress'

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/ingress/**/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Lint
        uses: ./.github/actions/cargo_lint
        with:
          packagePath: packages/ingress
