name: 'Deploy package: utils'

on:
  push:
    branches:
      - main
    paths:
      - packages/utils/**/*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Lint
        uses: ./.github/actions/cargo_lint
        with:
          packagePath: packages/utils

  publish:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Publish crate
        uses: ./.github/actions/cargo_publish
        with:
          packagePath: packages/utils
          cargoToken: ${{ secrets.CARGO_REGISTRY_TOKEN }}
