name: TP2 CI

on:
  push:
    paths:
      - TP2/**/*.rs

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TP2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Make lint
        run: make lint
